version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: rehearsal-scheduler-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rehearsal_scheduler
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: rehearsal-scheduler-server
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/rehearsal_scheduler
      NODE_ENV: development
      PORT: 4000
      JWT_SECRET: dev_jwt_secret_change_in_production
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: rehearsal-scheduler-client
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      REACT_APP_API_URL: http://localhost:4000
      NODE_ENV: development
    volumes:
      - ./client:/app
      - /app/node_modules